nilai1 = int(input("masukkan nilai pertama : "))
nilai2 = int(input("masukkan nilai kedua : "))
penjumlahan = nilai1 + nilai2
print(nilai1, "+", nilai2, "=", penjumlahan)
pengurangan = nilai1 - nilai2
print(nilai1, "-", nilai2, "=", pengurangan)
perkalian = nilai1 * nilai2
print(nilai1, "x", nilai2, "=", perkalian)
pembagian = nilai1 / nilai2
print(nilai1, "/", nilai2, "=", pembagian)
pemangkatan = nilai1 ** nilai2
print(nilai1, "**", nilai2, "=", pemangkatan)
pembagian_bulat = nilai1 // nilai2
print(nilai1, "//", nilai2, "=", pembagian_bulat)
